// Code generated by scripts/gen_cef_bindings.sh; DO NOT EDIT.

package cefbindings

// BrowserHandle is an opaque browser handle that wraps a CEF browser pointer.
type BrowserHandle uintptr

// BrowserOptions mirrors cef_runtime_browser_opts_t from runtime/cef_runtime.h.
type BrowserOptions struct {
	URL          string
	Title        string
	Width        int
	Height       int
	Frameless    bool
	Chromeless   bool
	Resizable    bool
	Fullscreen   bool
	Maximized    bool
	X            int
	Y            int
	ParentWindow uintptr
}

// DefaultBrowserOptions returns the CEF runtime defaults.
func DefaultBrowserOptions() BrowserOptions {
	return BrowserOptions{
		URL:       "about:blank",
		Width:     800,
		Height:    600,
		Resizable: true,
		X:         -1,
		Y:         -1,
	}
}
